steps:
  - name: "gcr.io/cloud-builders/docker"
    id: Build
    args:
      - "build"
      - "-t"
      - "gcr.io/$PROJECT_ID/my-fast-api:$SHORT_SHA"
      - "."

  # This step pushes the image to Container Registry

  - name: "gcr.io/cloud-builders/docker"
    id: Push
    args:
      - "push"
      - "gcr.io/$PROJECT_ID/my-fast-api:$SHORT_SHA"

  # generates the new manifest
  #the entrypoint in a build step to specify an entrypoint if you don't want to use the default entrypoint of the builder.
  #If you don't set this field, Cloud Build will use the builder's entrypoint.
  - name: "gcr.io/cloud-builders/gcloud"
    id: Generate manifest
    entrypoint: /bin/sh
    args:
      - "-c"
      - |
        sed "s/GOOGLE_CLOUD_PROJECT/${PROJECT_ID}/g" deployment.yaml.tpl | \
        sed "s/latest/${SHORT_SHA}/g" > deployment.yaml

  # deploys the new version of our container image in the Kubernetes Engine cluster.
  - name: "gcr.io/cloud-builders/kubectl"
    id: Deploy
    args: ["apply", "-f", "deployment.yaml"]
    env:
      - "CLOUDSDK_COMPUTE_ZONE=us-central1"
      - "CLOUDSDK_CONTAINER_CLUSTER=my-john-k8s-proof"