apiVersion: v1
kind: Service
metadata:
  name: my-fast-api-service
  namespace: fast-backend
spec:
  selector:
     run: my-fast-api
  ports:
  - protocol: TCP
    port: 8090
    targetPort: 8080
  type: LoadBalancer