apiVersion: v1
kind: Service
metadata:
  name: cache-memcached-service
  namespace: fast-backend
spec:
  selector:
    app: cache-memcached
  ports:
    - name: memcache-port
      port: 11211
      targetPort: 11211
    - name: metrics
      port: 9150
      targetPort: 9150